schema_version = "1.0.0"

id = "pataz_auto_hide_overlays"
version = "5.1.1"
name = "Pataz Auto Hide Overlays"
tagline = "Hides overlays during transform"
maintainer = "Daniel Salazar"
type = "add-on"

website = "https://www.patazanimation.com/"

tags = ["Animation"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2025 Daniel Salazar",]