schema_version = "1.0.0"

id = "auto_hide_overlays"
version = "5.1.0"
name = "Auto Hide Overlays"
tagline = "Hides overlays during transforms"
maintainer = "Daniel Salazar"
type = "add-on"

website = "https://www.patazanimation.com/"

tags = ["Animation"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2025 Daniel Salazar",]